### PR TITLE
Colin/auto deployments

### LINKED ISSUE #253: Auto deploy `solmate` math and `solstat`
These contracts will be so heavily used that we may as well deploy them for every environment.

- [x] Write a contract that exposes relevant functions in `solmate` fixed point math contract and `solstat` contract.
- [x] Generate bindings for this new contract.
- [x] Have `admin` deploy this contract automatically when doing `SimulationManager::new()`.
- [x] Gave the manager a `HashMap` of contracts.

### PR DESCRIPTION
**Pull request by Autoparallel**
Built a new contract just as an interface for some smart contract math. This new contract is called `ArbiterMath.sol`. A test for the functions appears in `simulate/lib.rs`.

~~Working to close #253 now, but I will have to edit things just a bit to auto-deploy these.~~

Closes #253

### CODE REVIEW

**Review by 0xJepsen — APPROVED** [review]
Looks like CI test fails for the code coverage 
```[2023-05-05T10:45:01.688Z] ['error'] There was an error running the uploader: Error uploading to [https://codecov.io:](https://codecov.io/) Error: There was an error fetching the storage URL during POST: 404 - {'detail': ErrorDetail(string='Unable to locate build via Github Actions API. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}
Error: Codecov: Failed to properly upload: The process '/home/runner/work/_actions/codecov/codecov-action/v3/dist/codecov' failed with exit code 255```

**Comment by Autoparallel** [comment]
@funkycadet  do you know why codecov is failing here?

**Comment by 0xJepsen** [comment]
> I believe its due to the absence of a codecov token for this repository. That should be added as a repository secret. Also, if it hasn't been done yet, the codecov app needs to be set up on this repository by the maintainers. I'm guessing that would be you. Once that's done, everything should work just fine.

Could you share some more information on this? Happy to tackle this but i haven't done this before.

**Comment by funkycadet** [comment]
> > I believe its due to the absence of a codecov token for this repository. That should be added as a repository secret. Also, if it hasn't been done yet, the codecov app needs to be set up on this repository by the maintainers. I'm guessing that would be you. Once that's done, everything should work just fine.
> 
> Could you share some more information on this? Happy to tackle this but i haven't done this before.

Sure. Since you're a collaborator on this repository, you would need to grant codecov access to this repository. Before you can do so, you would need to create an account with codecov. After that, you would see a list of all your repositories on codecov. Much of how its done is explained in their [documentation] (https://docs.codecov.com/docs). Look through it and let me know if it all makes sense so we can work on it together via Meet, if you don't mind

**Comment by 0xJepsen** [comment]
Got this passing, will resolve conflicts and merge

**Comment by funkycadet** [comment]
Yeah it does. I think more tests are needed. Could be why the cov is that low

**Comment by Autoparallel** [comment]
@0xJepsen is this able to be merged now?

**Comment by Autoparallel** [comment]
@0xJepsen can you please merge this?

**Review by 0xJepsen — APPROVED** [review]
lgtm

**Pull request merged**
