### PR TITLE
Moving functionality into Clairvoyance

### PR DESCRIPTION
**Pull request by Autoparallel**
This approaches #101 by abstracting a bit out of main.

### CODE REVIEW

**Review by 0xJepsen — APPROVED** [review]
I think this is a good approach!

**Review by ts0yu — COMMENTED** [review]
I like the general direction and am happy to merge for now but I think we need to consider the fact that clairvoyance is a library and needs to be oriented as such - maybe we could add this to utils?

**Comment by Autoparallel** [comment]
> I like the general direction and am happy to merge for now but I think we need to consider the fact that clairvoyance is a library and needs to be oriented as such - maybe we could add this to utils?

This is where your input is really helpful, @ts0yu ! Please feel free to make edits and show us the best way to organize.

I was following some of your layout with Architect, after all 😄

**Review by 0xJepsen — APPROVED** [review]
Clean love anything that reduces LOC

**Pull request merged**
