### PR TITLE
feat(contracts): arbiter token auto approve on transfers

### PR DESCRIPTION
**Pull request by Autoparallel**
**Give an overview of the tasks completed**
This PR adds the token spend approval upon `transfer` and `transferFrom` to cut down on additional approvals when using these tokens.

**Link to issue(s) that this PR closes**
N/A

### CODE REVIEW

**Comment by 0xJepsen** [comment]
What if there are bugs in a the way that some contracts are implementing approvals? do you think this is any edge case that would be good to have them separate for?

**Review by 0xJepsen — APPROVED** [review]
This looks good to me

**Comment by Autoparallel** [comment]
> What if there are bugs in a the way that some contracts are implementing approvals? do you think this is any edge case that would be good to have them separate for?

That's fair. Maybe it's better to just have the liquid exchange properly handle approvals instead then and not change in the token logic itself. Let me close this one.

**Comment by Autoparallel** [comment]
@jepsen, we might want to consider reopening this as you can't do the approvals in the exchanges.

**Pull request closed without merging**
