### PR TITLE
cleanup custom error types

### PR DESCRIPTION
**Pull request by ts0yu**
boom

### CODE REVIEW

**Comment by Autoparallel** [comment]
I'll review this in a bit! Looking clean though 😁

**Review by 0xJepsen — CHANGES_REQUESTED** [review]
this looks good to me! If you could bump the patch version i think we can get this moved in!

**Review by Autoparallel — APPROVED** [review]
looks great!

**Comment by Autoparallel** [comment]
@0xJepsen I bumped the `arbiter-core` patch since that was all that was touched. Feel free to review/merge.

**Review by 0xJepsen — APPROVED** [review]

**Pull request merged**
