### PR TITLE
bind on init

### PR DESCRIPTION
**Pull request by boyle-michael**
This pull request implements the changes requested in issue #428 by changing the `init` command to also redo the contract bindings.

### CODE REVIEW

**Comment by Autoparallel** [comment]
Let me clone this and give it a shot.

**Review by Autoparallel — APPROVED** [review]
Seems to work for me! 

Do you want to consider changing the README to reflect this change?

**Review by 0xJepsen — APPROVED** [review]
nice lgtm!

**Comment by 0xJepsen** [comment]
LEt's get CI passing and we can merge this in

**Pull request merged**
