### PR TITLE
Waylon/arbitrage

### PR DESCRIPTION
**Pull request by 0xJepsen**
working on the initial structure for this agent

### CODE REVIEW

**Comment by Autoparallel** [comment]
@0xJepsen you may not need a write thread for agents after this. My PR is changing some of this quite heavily.

**Comment by 0xJepsen** [comment]
> My PR is changing some of this quite heavily.

Nice, I feel like i am in a good place to start using the events from the liquid market in #154

**Review by Autoparallel — CHANGES_REQUESTED** [review]
Rename `arbitrage.rs` submodule to `arbitrageur.rs`.

**Review by Autoparallel — CHANGES_REQUESTED** [review]
Why are we adding the openzeppelin-contracts?

**Comment by 0xJepsen** [comment]
Closing for now

**Pull request closed without merging**
