### PR TITLE
feat: project structure refactor

### LINKED ISSUE #98: Filesystem clean up
After we are cooking with a basic simulation (e.g., arbitrage in #66), let's make sure we remove any and all files that we don't need (e.g., `./bin/*`). We should only need `*.rs` contract bindings.

### PR DESCRIPTION
**Pull request by ts0yu**
lets use this pr for our general project structure refactor

i renamed the `/src` folder to `/contracts` so we can maybe use the src for a cli binary

this might not be so simple though as we will have to mess around with the cargo.toml configuration which will clashes with the current workspace 

Closes #98

### CODE REVIEW

**Comment by ts0yu** [comment]
will eventually close https://github.com/primitivefinance/arbiter/issues/101

**Comment by 0xJepsen** [comment]
closes #98

**Comment by 0xJepsen** [comment]
lets merge this now that it closes one and until we all read more lets put the refactor in the ice box?

**Review by Autoparallel — APPROVED** [review]
Easy enough! Thanks!

**Comment by Autoparallel** [comment]
@ts0yu @0xJepsen @kinrezC I ran `cargo +nightly udeps` locally and cleaned up our cargo a bit. Someone please check this merge!

**Review by 0xJepsen — APPROVED** [review]
LGTM

**Pull request merged**
