### PR TITLE
Update init.rs ✨

### PR DESCRIPTION
**Pull request by 0xJepsen**
Fix init.rs
update paths

### CODE REVIEW

**Comment by 0xJepsen** [comment]
Closes #406

**Comment by 0xJepsen** [comment]
Maybe add a log to inform users that revert strings are on
https://github.com/primitivefinance/arbiter/blob/fd779c8effff44c8f8118e2465d84598559528f9/bin/bind.rs#L6C1-L7C1

**Comment by Autoparallel** [comment]
> Put bindings in .gitignore

did you do this @0xJepsen ?

**Review by Autoparallel — APPROVED** [review]
lgtm

**Pull request merged**
