### PR TITLE
refactoring manager and environment

### PR DESCRIPTION
**Pull request by ts0yu**
clean some stuff up

### CODE REVIEW

**Comment by Autoparallel** [comment]
Reviewing this now and cleaning up. This looks good.

**Comment by Autoparallel** [comment]
Pending the CI here, @0xJepsen can you also take a look?

**Review by Autoparallel — APPROVED** [review]
I did just a bit of clean up to this branch and added a `utils` module inside of the `Simulate` crate.. The changes are good. Changes to bindings was due to merging in from main and running `cargo fmt`.

**Comment by 0xJepsen** [comment]
> Pending the CI here, @0xJepsen can you also take a look?

Reviewing now

**Review by 0xJepsen — APPROVED** [review]
lgtm!

**Pull request merged**
